# Generated by Django 5.1.4 on 2025-01-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(blank=True, choices=[('a', 'asd'), ('b', 'asd')], max_length=100, null=True),
        ),
    ]
