# Generated by Django 5.1.4 on 2025-01-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_question_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(blank=True, choices=[('a', 'مشکل یا بیماری گیاهان'), ('b', 'نحوه نگهداری'), ('c', 'مواد مغذی گیاهان'), ('d', 'ظاهر گیاهان'), ('e', 'اطلاعات عمومی درباره گیاهان'), ('f', 'روش های تکثیر گیاهان'), ('g', 'زادگاه گیاهان'), ('h', 'خاک گیاه'), ('i', 'آب گیاه'), ('j', 'نور گیاه'), ('k', 'دما و رطوبت گیاه'), ('l', 'هرس کردن گیاه'), ('m', 'محصولات گیاه'), ('n', 'نام کاشف'), ('o', 'محل اکتشاف'), ('p', 'نام علمی گیاهان'), ('q', 'نام فارسی گیاهان')], max_length=100, null=True),
        ),
    ]
