# Generated by Django 5.1.4 on 2025-01-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='light',
            field=models.TextField(default='medium'),
        ),
        migrations.AddField(
            model_name='plants',
            name='persian_name',
            field=models.CharField(default='گیاه', max_length=100),
        ),
        migrations.AddField(
            model_name='plants',
            name='scientific_name',
            field=models.CharField(default='none', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='plants',
            name='soil',
            field=models.TextField(default='wet'),
        ),
        migrations.AddField(
            model_name='plants',
            name='temperature',
            field=models.TextField(default='medium'),
        ),
        migrations.AddField(
            model_name='plants',
            name='water',
            field=models.TextField(default='medium'),
        ),
    ]
