# Generated by Django 5.1.4 on 2025-01-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_plants', '0002_plants_light_plants_persian_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='plant_image',
            field=models.ImageField(blank=True, null=True, upload_to='plant_images/'),
        ),
    ]
