# Generated by Django 5.1.4 on 2025-01-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_plants', '0005_remove_plants_family_remove_plants_genus'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='deseases',
            field=models.TextField(default=''),
        ),
    ]
