# Generated by Django 5.1.5 on 2025-01-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_plants', '0006_plants_deseases'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='light',
            field=models.CharField(blank=True, choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='plants',
            name='soil_type',
            field=models.CharField(blank=True, choices=[('Loamy Soil', 'Loamy Soil'), ('Sandy Soil', 'Sandy Soil'), ('Clay Soil', 'Clay Soil'), ('Peat Soil', 'Peat Soil')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='plants',
            name='temperature',
            field=models.CharField(blank=True, choices=[('warm', 'warm'), ('medium', 'medium'), ('cold', 'cold')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='plants',
            name='water',
            field=models.CharField(blank=True, choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], default='', max_length=100),
        ),
    ]
