# Generated by Django 5.1.5 on 2025-02-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_plants', '0007_plants_light_plants_soil_type_plants_temperature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='light',
            field=models.CharField(blank=True, choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='plants',
            name='soil_type',
            field=models.CharField(blank=True, choices=[('Loamy Soil', 'خاک لومی'), ('Sandy Soil', 'خاک ماسه ای'), ('Clay Soil', 'خاک رس'), ('Peat Soil', 'خاک پیت'), ('Chalky soil', 'خاک گچی'), ('Silty Soil', 'خاک سیلتی')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='plants',
            name='temperature',
            field=models.CharField(blank=True, choices=[('warm', 'گرم'), ('medium', 'متوسط'), ('cold', 'سرد')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='plants',
            name='water',
            field=models.CharField(blank=True, choices=[('high', 'زیاد'), ('medium', 'متوسط'), ('low', 'کم')], default='', max_length=100),
        ),
    ]
