# Generated by Django 5.1.5 on 2025-02-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_plants', '0008_alter_plants_light_alter_plants_soil_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='soil_type',
            field=models.CharField(blank=True, choices=[('Loamy Soil', 'خاک لومی'), ('Sandy Soil', 'خاک ماسه ای'), ('Clay Soil', 'خاک رس'), ('Peat Soil', 'خاک پیت'), ('Chalky soil', 'خاک گچی'), ('Silty Soil', 'خاک سیلتی'), ('no soil', 'بدون خاک')], default='', max_length=100),
        ),
    ]
