# Generated by Django 5.1.5 on 2025-01-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approachs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approach',
            name='positive_or_negative',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
