# Generated by Django 5.1.5 on 2025-01-27 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approachs', '0002_approach_positive_or_negative'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproachAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(default='none')),
                ('approach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='approachs.approach')),
            ],
        ),
    ]
