# Generated by Django 5.1.5 on 2025-01-27 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approachs', '0003_approachanswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApproachAnswer',
        ),
    ]
