# Generated by Django 5.1.5 on 2025-01-27 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approachs', '0004_delete_approachanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproachAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approach_answer', models.TextField(default=None)),
                ('approach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approach_answer', to='approachs.approach')),
            ],
        ),
    ]
