# Generated by Django 5.1.5 on 2025-01-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approachs', '0005_approachanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approachanswer',
            name='approach_answer',
            field=models.TextField(default='هنوز پاسخی وجود ندارد'),
        ),
    ]
