# Generated by Django 5.1.5 on 2025-02-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approachs', '0006_alter_approachanswer_approach_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approachanswer',
            name='approach_answer',
            field=models.TextField(default=None),
        ),
    ]
