# Generated by Django 5.1.5 on 2025-01-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLDdetector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantDiseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('causes', models.TextField()),
                ('detection', models.TextField()),
                ('management', models.TextField()),
                ('refrense', models.TextField()),
            ],
        ),
    ]
