# Generated by Django 5.1.5 on 2025-01-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLDdetector', '0002_plantdiseases'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantdiseases',
            name='image',
            field=models.ImageField(default='none', upload_to='plant_disease_image'),
        ),
        migrations.AddField(
            model_name='plantdiseases',
            name='symptoms',
            field=models.TextField(blank=True, default='فعلا اطلاعاتی در دسترس نیست', null=True),
        ),
        migrations.AlterField(
            model_name='plantdiseases',
            name='causes',
            field=models.TextField(default='فعلا اطلاعاتی در دسترس نیست'),
        ),
        migrations.AlterField(
            model_name='plantdiseases',
            name='detection',
            field=models.TextField(blank=True, default='فعلا اطلاعاتی در دسترس نیست', null=True),
        ),
        migrations.AlterField(
            model_name='plantdiseases',
            name='management',
            field=models.TextField(default='فعلا اطلاعاتی در دسترس نیست'),
        ),
    ]
