# Generated by Django 5.1.5 on 2025-01-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLDdetector', '0003_plantdiseases_image_plantdiseases_symptoms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantdiseases',
            name='persian_name',
            field=models.CharField(blank=True, default='هنوز نام فارسی وجود ندارد', max_length=100, null=True),
        ),
    ]
