# Generated by Django 5.1.5 on 2025-01-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLDdetector', '0004_plantdiseases_persian_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantdiseases',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
