# Generated by Django 5.1.5 on 2025-01-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLDdetector', '0005_plantdiseases_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdiseases',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
