# Generated by Django 5.1.5 on 2025-01-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PLDdetector', '0007_alter_plantdiseases_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantdiseases',
            name='description',
        ),
    ]
