# Generated by Django 5.1.5 on 2025-01-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLDdetector', '0008_remove_plantdiseases_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdiseases',
            name='common_name',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
