# Generated by Django 5.1.5 on 2025-01-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PLDdetector', '0009_alter_plantdiseases_common_name'),
    ]

    operations = [
    ]
