# Generated by Django 5.1.3 on 2024-11-23 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_phone_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='iamge',
            new_name='image',
        ),
    ]
