# Generated by Django 5.1.4 on 2025-01-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_iamge_profile_image'),
        ('my_plants', '0002_plants_light_plants_persian_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='users_plants',
            field=models.ManyToManyField(blank=True, to='my_plants.plants'),
        ),
    ]
